export interface Post {
  _id: string
  title: string
  date: string
  excerpt: string
  slug: string
  tags?: string[]
  body?: {
    code: string
  }
}

export interface Experience {
  _id: string
  company: string
  position: string
  startDate: string
  endDate: string | null
  description: string
  achievements: string[]
}

export interface Project {
  id: number
  title: string
  description: string
  image: string
  link: string
  tags: string[]
  featured?: boolean
}

// Sample data that would normally be generated by Contentlayer
export const samplePosts: Post[] = [
  {
    _id: "post-1",
    title: "Getting Started with Next.js",
    date: "2023-01-15",
    excerpt: "Learn how to build modern web applications with Next.js",
    slug: "getting-started-with-nextjs",
    tags: ["Next.js", "React", "Web Development"],
  },
  {
    _id: "post-2",
    title: "Styling with Tailwind CSS",
    date: "2023-02-10",
    excerpt: "How to use Tailwind CSS to create beautiful, responsive designs",
    slug: "styling-with-tailwind-css",
    tags: ["CSS", "Tailwind", "Design"],
  },
  {
    _id: "post-3",
    title: "Server Components in Next.js",
    date: "2023-03-05",
    excerpt: "Understanding the power of React Server Components in Next.js",
    slug: "server-components-nextjs",
    tags: ["Next.js", "React", "Server Components"],
  },
]

export const sampleExperiences: Experience[] = [
  {
    _id: "exp-1",
    company: "Example Company",
    position: "Senior Developer",
    startDate: "2021-01-01",
    endDate: "2023-01-01",
    description: "Led development of key features for the company's flagship product.",
    achievements: [
      "Increased site performance by 40% through code optimization",
      "Implemented CI/CD pipeline reducing deployment time by 60%",
      "Mentored junior developers and conducted code reviews",
    ],
  },
  {
    _id: "exp-2",
    company: "Previous Company",
    position: "Frontend Developer",
    startDate: "2018-06-01",
    endDate: "2020-12-31",
    description: "Developed responsive web applications using React and TypeScript.",
    achievements: [
      "Built reusable component library used across multiple projects",
      "Implemented state management using Redux",
      "Collaborated with design team to improve UX",
    ],
  },
]

