export const experiencesList = [
  {
    _id: 'exp-1',
    company: 'Shopee',
    position: 'Software Engineer Trainee',
    startDate: '2025-02-01',
    endDate: '2025-03-31',
    description: 'Leading e-commerce platform in Southeast Asia and Taiwan.',
    achievements: [
      `Selected as one of 28+ trainees to attend Shopee - SEA Labs Indonesia's competitive training program for software engineers.`,
      'Learn full-stack development using Go and React, along with SRE best-practices.',
    ],
    logoUrl: './company/Shopee.svg',
    website: 'https://www.sea.com/products/shopee',
    category: 'professional',
  },
  {
    _id: 'exp-1',
    company: 'Shopee',
    position: 'Software Engineer Trainee',
    startDate: '2025-07-01',
    endDate: '',
    description: 'Leading e-commerce platform in Southeast Asia and Taiwan.',
    achievements: [],
    logoUrl: './company/Shopee.svg',
    website: 'https://www.sea.com/products/shopee',
    category: 'professional',
  },
  {
    _id: 'exp-2',
    company: 'Bank Mandiri',
    position: 'Software Engineer Intern',
    startDate: '2024-09-01',
    endDate: '2024-12-31',
    description: 'Biggest bank in Indonesia in terms of assets ($35.16B market cap).',
    achievements: [
      'Contributed to the RPA KCTT project using UiPath, automating the KCTT reject data recapitulation process, reducing manual effort by approximately 80% and cutting processing time by 50%.',
      'Developed automation solutions for IPA uploading, streamlining workflows to handle 30+ uploads with zero errors post-implementation.',
      'Achieved recognition as one of the top interns in the IT School program, standing out among 3/4 sessions for exceptional performance and contributions.',
    ],
    logoUrl: '/company/Mandiri.webp',
    website: 'https://www.bankmandiri.co.id/',
    category: 'professional',
  },
  {
    _id: 'exp-3',
    company: 'The Directorate General of Treasury (DJPb), Ministry of Finance',
    position: 'Mobile Developer - Contract',
    startDate: '2024-08-01',
    endDate: '2024-09-31',
    description: 'Government institution in Indonesia.',
    achievements: [
      'Engineered critical features including network state management, session validation, and search, increasing app performance and reducing data loading times by approximately 30%.',
      'Improved system reliability by identifying and resolving 5+ production issues, ensuring 99.9% app uptime and smooth user experiences.',
      'Optimized user workflows through intuitive search and filter features, reducing time spent accessing key bansos data and reports by an estimated 40%.',
    ],
    logoUrl: '/company/Kemenkeu.png',
    website: 'https://www.kemenkeu.go.id/home',
    category: 'professional',
  },
  {
    _id: 'exp-4',
    company: 'Televisi Republik Indonesia (TVRI)',
    position: 'Mobile Engineer - Contract',
    startDate: '2024-07-01',
    endDate: '2024-09-31',
    description: `Indonesia's national public broadcasting service.`,
    achievements: [
      'Engineered core app features using Flutter, including task management, task submission, and survey management, streamlining workflows and potentially boosting team productivity by an estimated 20%.',
      'Designed and implemented offline capabilities with auto-resync and local preferences, improving app usability and reliability in low-connectivity environments.',
      'Achieved over 100+ installations on Google Play Store within the first release, demonstrating successful adoption and user trust.',
    ],
    logoUrl: '/company/TVRI.png',
    website: 'https://tvri.go.id/',
    category: 'professional',
  },
  {
    _id: 'exp-5',
    company: 'Bangkit Academy led by Google, Tokopedia, Gojek, and Traveloka',
    position: 'Mobile Development Cohort',
    startDate: '2024-02-01',
    endDate: '2024-07-31',
    description: 'Growing world-class tech talent in Indonesia with Kampus Merdeka.',
    achievements: [
      'Learned Kotlin and Firebase to engineer scalable, user-centric mobile applications, emphasizing robust software engineering and UI/UX design principles.',
      'Collaborated effectively in a dynamic cohort environment, refining teamwork and critical thinking skills essential for professional mobile development.',
      'Spearheaded the development of HouseSpot as a capstone project, showcasing real-world problem solving and innovative mobile app design.',
    ],
    logoUrl: '/company/BangkitLogo.png',
    website: 'https://grow.google/intl/id_id/bangkit/?tab=mobile-development',
    category: 'professional',
  },
  {
    _id: 'exp-6',
    company: 'Faculty of Computer Science University of Indonesia',
    position: 'Teaching Assistant',
    startDate: '2022-08-01',
    endDate: '2024-06-31',
    description: 'Shaping excellence in computer science education and research.',
    achievements: [
      'Mentored 3 student groups (15+ students) in core HCI and user-centered design, driving enhanced project quality and academic alignment.',
      'Guided 14 students through Java and OOP principles by designing targeted lab assignments that reinforced key concepts.',
      'Led 13 students through an intensive Python curriculum, with tailored lab projects contributing to top midterm and final scores.',
    ],
    logoUrl: '/company/TAUI.jpeg',
    website: 'https://cs.ui.ac.id/',
    category: 'professional',
  },
  {
    _id: 'exp-7',
    company: 'University of Indonesia',
    position: 'Bachelor of Computer Science',
    startDate: '2021-08-01',
    endDate: '',
    description: 'Veritas, Probitas, Iustitia.',
    achievements: [
      'cGPA: 3.74 (Cumlaude)',
      'Activities and societies: RISTEK CS UI, FUKI CS UI, COMPFEST, Pesta Rakyat Komputer, AIESEC, Teaching Assistant',
      'Thesis: Integration Between Product Line and Product Line Authentication Improvements After Dependency Changes in Prices-IDE (Grade: A)',
    ],
    logoUrl: '/education/fasilkom.png',
    website: 'https://cs.ui.ac.id/',
    category: 'education',
  },
  {
    _id: 'exp-8',
    company: 'SMA S Al Kautsar Bandar Lampung',
    position: 'High School Student',
    startDate: '2018-08-01',
    endDate: '2021-08-01',
    description: 'Unggul, Islami, Global.',
    achievements: [
      'Graduated as Top 5 Best Students academically in the school.',
      'Participated as finalist in national-level Informatics Olympiad 2020.',
      'Won various regional and national competitions in Informatics and Islamic competition.',
    ],
    logoUrl: '/education/aka.jpg',
    website: 'https://www.smas-alkautsar.sch.id/',
    category: 'education',
  },
  {
    _id: 'exp-9',
    company: 'RISTEK Fasilkom UI',
    position: 'Lead of Mobile Development',
    startDate: '2023-03-01',
    endDate: '2025-02-01',
    description: 'The biggest and coolest IT student organization in Indonesia.',
    achievements: [],
    logoUrl: '/org/ristek.png',
    website: 'https://www.ristek.cs.ui.ac.id/',
    category: 'volunteer',
  },
  {
    _id: 'exp-10',
    company: 'FUKI Fasilkom UI',
    position: 'Director of IT Force',
    startDate: '2023-03-01',
    endDate: '2024-02-01',
    description:
      'Student organization that aims to accelerate the growth of students in the fields of religion-technology.',
    achievements: [],
    logoUrl: '/org/fukilogo.png',
    website: 'https://www.fuki.cs.ui.ac.id/',
    category: 'volunteer',
  },
  {
    _id: 'exp-11',
    company: 'COMPFEST',
    position: 'Visual Designer',
    startDate: '2022-03-01',
    endDate: '2023-01-01',
    description: 'The biggest and leading one stop IT event held by students.',
    achievements: [],
    logoUrl: '/org/compfestlogo.jpeg',
    website: 'https://www.compfest.id/',
    category: 'volunteer',
  },
  {
    _id: 'exp-12',
    company: 'Pekan Rakyat Komputer (PERAK) CS UI',
    position: 'Expert Visual Designer',
    startDate: '2023-02-01',
    endDate: '2023-10-01',
    description:
      "Fasilkom UI's annual event presents various exciting activities to strengthen togetherness.",
    achievements: [],
    logoUrl: '/org/pesta_rakyat_komputer_logo.jpeg',
    website: 'https://www.perak.id/',
    category: 'volunteer',
  },
  {
    _id: 'exp-13',
    company: 'AIESEC UI',
    position: 'Future Leaders Delegate',
    startDate: '2024-10-01',
    endDate: '2025-01-01',
    description:
      'Global youth-led organization striving to achieve peace and fulfillment of humankind’s potential by activating leadership qualities in youth.',
    achievements: [],
    logoUrl: '/org/aiesec_ui.jpg',
    website: 'https://aiesec.or.id/',
    category: 'volunteer',
  },
  {
    _id: 'exp-14',
    company: 'Dasar-Dasar Pemrograman 0',
    position: 'Mentor',
    startDate: '2022-07-01',
    endDate: '2022-08-01',
    description:
      "A non-compulsory introductory course in programming for Fasilkom Universitas Indonesia's first-year students.",
    achievements: [],
    logoUrl: '/org/ddp0fasilkomui_logo.jpeg',
    website: 'https://www.linkedin.com/company/ddp0fasilkomui/',
    category: 'volunteer',
  },
  {
    _id: 'exp-15',
    company: 'BEM Fasilkom UI',
    position: 'Media Bureau Intern',
    startDate: '2021-09-01',
    endDate: '2021-12-01',
    description:
      'An organization for Fasilkom UI students to serve and create meaningful creations for the benefits of Fasilkom UI by leveraging information technology.',
    achievements: [],
    logoUrl: '/org/logo-bem.png',
    website: 'https://bem.cs.ui.ac.id/',
    category: 'volunteer',
  },
];

export const projectList = [
  {
    id: 1,
    title: 'Citizen Journalism Mobile',
    description: `A flutter app designed to streamline news reporting, delivering real-time updates from TVRI.`,
    image: '/project/citizen-journalism.png?height=300&width=500',
    link: 'https://play.google.com/store/apps/details?id=com.tvri.citizenjournalism&hl=en&pli=1',
    tags: ['Flutter', 'Quill RTE', 'Cubit', 'Local Database'],
  },
  {
    id: 2,
    title: 'Bikun Tracker Mobile',
    description:
      'A flutter app designed to keep track of the mobilization of Bis Kuning (Bikun) in University of Indonesia.',
    image: '/project/bikuntracker.png?height=300&width=500',
    link: 'https://bikun.ui.ac.id/',
    tags: ['Flutter', 'Websocket', 'Google API', 'Firebase'],
  },
  {
    id: 3,
    title: 'Questify',
    description:
      'A startup project that aims to empower academic community engagement through a redefined prize-based questionnaire platform.',
    image: '/project/questify.png?height=300&width=500',
    link: 'https://questify-ppl.vercel.app/',
    tags: ['Next.js', 'NestJS', 'TypeScript', 'TDD'],
  },
  {
    id: 4,
    title: 'HouseSpot',
    description:
      'A mobile app designed to simplify homeownership by estimating house prices, connecting with reliable vendors, and discovering related home products and services.',
    image: '/project/housespot.png?height=300&width=500',
    link: 'https://github.com/HouseSpot/kotlin-mobile-fe/releases',
    tags: ['Kotlin', 'Google API', 'ExpressJS', 'GCP'],
  },
  {
    id: 5,
    title: 'Mobile Bansos',
    description:
      'A flutter app to streamline the distribution and management of social assistance (bansos) in Indonesia.',
    image: '/project/mobile-bansos.png?height=300&width=500',
    link: '',
    tags: ['Flutter', 'Cache Management'],
  },
  {
    id: 6,
    title: 'Pet Daycare',
    description:
      'A web app project for pet daycare service with various payment capabilities such as Pet Coins, Voucher, Gopay, Dana, etc.',
    image: '/project/pet-daycare.png?height=300&width=500',
    link: 'https://frontend-adpro-b10.vercel.app/',
    tags: ['Next.js', 'Java Springboot', 'Design Pattern'],
  },
  {
    id: 7,
    title: 'IO Dentistry FKG UI',
    description:
      'A web app to showcase information on the Faculty of Dentistry at Universitas Indonesia for international students.',
    image: '/project/fkg-io.png?height=300&width=500',
    link: 'https://io-dentistry-ui.com/',
    tags: ['React', 'Static Site'],
  },

  {
    id: 8,
    title: 'Share Eat',
    description:
      'A flutter app aimed to resolve issues on food losses & food wastes launched at MACS-G20.',
    image: '/project/share-eat.png?height=300&width=500',
    link: 'https://www.canva.com/design/DAFUgiJEGFg/8YpQFP3n-oyjywJQzvpqGw/view?utm_content=DAFUgiJEGFg&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h11c54749bb',
    tags: ['Flutter', 'Django'],
  },
];
