export const professionalExperiencesList = [
  {
    _id: 'exp-1',
    company: 'Faculty of Computer Science University of Indonesia',
    position: 'Teaching Assistant',
    startDate: '2022-08-01',
    endDate: '2024-06-30',
    description: 'Shaping excellence in computer science education and research.',
    achievements: [
      'Mentored **3 student groups (15+ students)** in core HCI and user-centered design, driving enhanced project quality and academic alignment.',
      '**Guided 14 students** through Java and OOP principles by designing targeted lab assignments that reinforced key concepts.',
      '**Led 13 students** through an intensive Python curriculum, with tailored lab projects **contributing to top midterm and final scores.**',
    ],
    logoUrl: '/company/TAUI.jpeg',
    website: 'https://cs.ui.ac.id/',
    type: 'Part-time',
  },

  {
    _id: 'exp-2',
    company: 'Bangkit Academy led by Google, Tokopedia, Gojek, and Traveloka',
    position: 'Mobile Development Cohort',
    startDate: '2024-02-01',
    endDate: '2024-07-31',
    description: 'Growing world-class tech talent in Indonesia with Kampus Merdeka.',
    achievements: [
      'Learned Kotlin and Firebase to engineer **scalable, user-centric mobile applications,** emphasizing robust software engineering and UI/UX design principles.',
      '**Collaborated effectively** in a dynamic cohort environment, refining teamwork and critical thinking skills essential for **professional mobile development.**',
      'Spearheaded the development of HouseSpot as a capstone project, showcasing **real-world problem solving** and **innovative mobile app** design.',
    ],
    logoUrl: '/company/BangkitLogo.png',
    website: 'https://grow.google/intl/id_id/bangkit/?tab=mobile-development',
    type: 'Academy',
  },

  {
    _id: 'exp-3',
    company: 'Televisi Republik Indonesia (TVRI)',
    position: 'Software Engineer',
    startDate: '2024-07-01',
    endDate: '2024-09-30',
    description: `Indonesia's national public broadcasting service.`,
    achievements: [
      'Engineered core app features using Flutter, including task management, task submission, and survey management, streamlining workflows and estimating a **20% boost** in team productivity.',
      'Designed and implemented **offline capabilities** with auto-resync and local preferences, improving **app usability** and **reliability** in low-connectivity environments.',
      'Achieved over **1000+ installations** on Google Play Store within the first release, demonstrating successful adoption and user trust.',
    ],
    logoUrl: '/company/TVRI.png',
    website: 'https://tvri.go.id/',
    type: 'Contract',
  },

  {
    _id: 'exp-4',
    company: 'Ministry of Finance',
    position: 'Software Engineer',
    startDate: '2024-08-01',
    endDate: '2024-09-30',
    description: 'Government institution in Indonesia.',
    achievements: [
      'Engineered **core features** including network state management, session validation, and search, increasing **app performance** and **reducing data loading times** by approximately **30%.**',
      'Improved system reliability by identifying and resolving **5+ development issues**, ensuring **99.9% app uptime** and smooth user experiences.',
      'Optimized user workflows through intuitive search and filter features, **reducing time spent accessing key bansos data and reports** by an estimated **40%.**',
    ],
    logoUrl: '/company/Kemenkeu.png',
    website: 'https://www.kemenkeu.go.id/home',
    type: 'Contract',
  },

  {
    _id: 'exp-5',
    company: 'Bank Mandiri',
    position: 'Software Engineer',
    startDate: '2024-09-01',
    endDate: '2024-12-31',
    description: 'Biggest bank in Indonesia in terms of assets ($26.68B market cap).',
    achievements: [
      'Architected an automated reconciliation pipeline handling signature verification (KCTT) using **UiPath** with **C#**, reducing manual processing load by **80%** and eliminating human data entry errors.',
      'Engineered automation solutions for document uploading, capable of handling **100+ daily uploads** with **100% accuracy**, eliminating manual entry bottlenecks.',
      'Achieved recognition as **one of the top interns** in the IT School program, standing out for exceptional performance and contributions.',
    ],
    logoUrl: '/company/Mandiri.webp',
    website: 'https://www.bankmandiri.co.id/',
    type: 'Internship',
  },
  {
    _id: 'exp-6',
    company: 'Shopee',
    position: 'Software Engineer',
    startDate: '2025-02-01',
    endDate: '2025-03-31',
    description: 'Leading e-commerce platform in Southeast Asia and Taiwan ($79.90B market cap).',
    achievements: [
      'Emerged as the **Top Graduate (1st place) among 28+ trainees** selected from **1,000+ applicants (<3% acceptance rate)** for the intensive Sea Labs engineering bootcamp.',
      "Architected 'Medisea' (**Go/React**), a pharmaceutical marketplace, implementing **enterprise-grade resilience patterns** including **circuit breakers** and **exponential backoff**. Designed a **thread-safe in-memory caching** layer to reduce downstream latency.",
      'Optimized critical backend endpoints using **k6**, reducing **P95 latency by 85% (700ms to <100ms)** under heavy load conditions.',
    ],
    logoUrl: './company/Shopee.svg',
    website: 'https://www.sea.com/products/shopee',
    type: 'Internship',
  },
];

export const educationExperiencesList = [
  {
    _id: 'edu-1',
    company: 'University of Indonesia',
    position: 'Bachelor of Computer Science',
    startDate: '2021-08-01',
    endDate: '',
    description: 'Veritas, Probitas, Iustitia.',
    achievements: [
      'cGPA: **3.74** (Cumlaude)',
      'Activities and societies: RISTEK CS UI, FUKI CS UI, COMPFEST, Pesta Rakyat Komputer, AIESEC, Teaching Assistant',
      'Thesis: Integration Between Product Line and Product Line Authentication Improvements After Dependency Changes in Prices-IDE **(Grade: A)**',
    ],
    logoUrl: '/education/fasilkom.png',
    website: 'https://cs.ui.ac.id/',
  },
  {
    _id: 'edu-2',
    company: 'SMA S Al Kautsar Bandar Lampung',
    position: 'High School Student',
    startDate: '2018-08-01',
    endDate: '2021-08-01',
    description: 'Unggul, Islami, Global.',
    achievements: [
      'Graduated as **Top 5 Best Students** academically in the school.',
      'Participated as **finalist** in national-level Informatics Olympiad 2020.',
      '**Won various regional and national competitions** in Informatics and Islamic competition.',
    ],
    logoUrl: '/education/aka.jpg',
    website: 'https://www.smas-alkautsar.sch.id/',
  },
];

export const volunteerExperiencesList = [
  {
    _id: 'exp-9',
    company: 'RISTEK Fasilkom UI',
    position: 'Lead of Mobile Development',
    startDate: '2024-02-01',
    endDate: '2025-02-01',
    description: 'The biggest and coolest IT student organization in Indonesia.',
    achievements: [],
    logoUrl: '/org/ristek.png',
    website: 'https://www.ristek.cs.ui.ac.id/',
  },
  {
    _id: 'exp-9',
    company: 'RISTEK Fasilkom UI',
    position: 'Member of Mobile Development',
    startDate: '2023-03-01',
    endDate: '2025-02-01',
    description: 'The biggest and coolest IT student organization in Indonesia.',
    achievements: [],
    logoUrl: '/org/ristek.png',
    website: 'https://www.ristek.cs.ui.ac.id/',
  },
  {
    _id: 'exp-10',
    company: 'FUKI Fasilkom UI',
    position: 'Director of IT Force',
    startDate: '2023-03-01',
    endDate: '2024-02-01',
    description:
      'Student organization that aims to accelerate the growth of students in the fields of religion-technology.',
    achievements: [],
    logoUrl: '/org/fukilogo.png',
    website: 'https://www.fuki.cs.ui.ac.id/',
  },
  {
    _id: 'exp-11',
    company: 'COMPFEST',
    position: 'Visual Designer',
    startDate: '2022-03-01',
    endDate: '2023-01-01',
    description: 'The biggest and leading one stop IT event held by students.',
    achievements: [],
    logoUrl: '/org/compfestlogo.jpeg',
    website: 'https://www.compfest.id/',
  },
  {
    _id: 'exp-12',
    company: 'Pekan Rakyat Komputer (PERAK) CS UI',
    position: 'Expert Visual Designer',
    startDate: '2023-02-01',
    endDate: '2023-10-01',
    description:
      "Fasilkom UI's annual event presents various exciting activities to strengthen togetherness.",
    achievements: [],
    logoUrl: '/org/pesta_rakyat_komputer_logo.jpeg',
    website: 'https://www.perak.id/',
  },
  {
    _id: 'exp-13',
    company: 'AIESEC UI',
    position: 'Future Leaders Delegate',
    startDate: '2024-10-01',
    endDate: '2025-01-01',
    description:
      "Global youth-led organization striving to achieve peace and fulfillment of humankind's potential by activating leadership qualities in youth.",
    achievements: [],
    logoUrl: '/org/aiesec_ui.jpg',
    website: 'https://aiesec.or.id/',
  },
  {
    _id: 'exp-14',
    company: 'Dasar-Dasar Pemrograman 0',
    position: 'Mentor',
    startDate: '2022-07-01',
    endDate: '2022-08-01',
    description:
      "A non-compulsory introductory course in programming for Fasilkom Universitas Indonesia's first-year students.",
    achievements: [],
    logoUrl: '/org/ddp0fasilkomui_logo.jpeg',
    website: 'https://www.linkedin.com/company/ddp0fasilkomui/',
  },
  {
    _id: 'exp-15',
    company: 'BEM Fasilkom UI',
    position: 'Media Bureau Intern',
    startDate: '2021-09-01',
    endDate: '2021-12-01',
    description:
      'An organization for Fasilkom UI students to serve and create meaningful creations for the benefits of Fasilkom UI by leveraging information technology.',
    achievements: [],
    logoUrl: '/org/logo-bem.png',
    website: 'https://bem.cs.ui.ac.id/',
  },
];

// Combined list for backward compatibility - adds category field
export const experiencesList = [
  ...professionalExperiencesList.map((exp) => ({ ...exp, category: 'professional' as const })),
  ...educationExperiencesList.map((exp) => ({ ...exp, category: 'education' as const })),
  ...volunteerExperiencesList.map((exp) => ({ ...exp, category: 'volunteer' as const })),
];

// Featured project IDs - update this array to select which projects appear on the home page
export const featuredProjectIds: number[] = [9, 8, 7, 6];

export const projectList = [
  {
    id: 1,
    title: 'Share Eat',
    slug: 'share-eat',
    description:
      'A sustainability-focused solution launched based on MACS-G20 to actively combat food loss and waste through smart resource management.',
    image: '/project/share-eat.png',
    link: 'https://www.canva.com/design/DAFUgiJEGFg/8YpQFP3n-oyjywJQzvpqGw/view?utm_content=DAFUgiJEGFg&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h11c54749bb',
    tags: ['Flutter', 'Django', 'Python', 'Dart'],
    year: 2022,
  },
  {
    id: 2,
    title: 'MovieTek',
    slug: 'movietek',
    description:
      'A mobile app to discover your next binge-worthy obsession with a sleek, all-in-one guide to the world of movies and TV series.',
    image: '/project/movietek.png',
    link: 'https://github.com/achievagemilang/movietek',
    tags: ['Flutter', 'Dart'],
    year: 2023,
  },
  {
    id: 3,
    title: 'Pet Daycare',
    slug: 'pet-daycare',
    description:
      'A versatile pet care platform featuring a flexible payment ecosystem that integrates Pet Coins, vouchers, and major e-wallets.',
    image: '/project/pet-daycare.png',
    link: 'https://frontend-adpro-b10.vercel.app/',
    tags: ['Next.js', 'Spring Boot', 'Java', 'TypeScript', 'Tailwind', 'PostgreSQL'],
    year: 2023,
  },
  {
    id: 4,
    title: 'Mobile Bansos',
    slug: 'mobile-bansos',
    description:
      'A digital infrastructure designed to ensure the transparent, efficient, and targeted distribution of social assistance across Indonesia.',
    image: '/project/djpb.jpg',
    link: 'https://www.kemenkeu.go.id/',
    tags: ['Flutter', 'Dart'],
    year: 2024,
  },
  {
    id: 5,
    title: 'HouseSpot',
    slug: 'housespot',
    description:
      'An end-to-end property companion that simplifies homeownership by combining price estimation, trusted vendor connections, and marketplace discovery.',
    image: '/project/housespot.png',
    link: 'https://github.com/HouseSpot/kotlin-mobile-fe/releases',
    tags: ['Kotlin', 'GCP', 'ExpressJS', 'JavaScript'],
    year: 2024,
  },
  {
    id: 6,
    title: 'Questify',
    slug: 'questify',
    description:
      'A gamified research platform that redefines academic engagement by connecting communities through incentivized, prize-based questionnaires.',
    image: '/project/questify.png',
    link: 'https://questify-ppl.vercel.app/',
    tags: ['Next.js', 'NestJS', 'TypeScript', 'Prisma', 'PostgreSQL', 'GCP', 'Grafana'],
    year: 2024,
  },
  {
    id: 7,
    title: 'Bikun Tracker Mobile',
    slug: 'bikun-tracker-mobile',
    description:
      "A real-time mobility companion for the University of Indonesia, helping students track and navigate the 'Bis Kuning' campus bus network.",
    image: '/project/bikuntracker.png',
    link: 'https://bikun.ui.ac.id/',
    tags: ['Flutter', 'Go', 'WebSocket', 'GCP', 'Dart', 'Firebase'],
    year: 2024,
  },
  {
    id: 8,
    title: 'Citizen Journalism',
    slug: 'citizen-journalism',
    description: `A modern digital portal delivering high-speed, real-time news reporting and updates directly from the TVRI network.`,
    image: '/project/citizen-journalism.png',
    link: 'https://play.google.com/store/apps/details?id=com.tvri.citizenjournalism&hl=en&pli=1',
    tags: ['Flutter', 'Go', 'Dart'],
    year: 2024,
  },

  {
    id: 9,
    title: 'Medisea',
    slug: 'medisea',
    description: `A high-performance pharmaceutical marketplace engineered with enterprise-grade fault tolerance to support secure transactions and sub-100ms latency for 100K+ monthly active users.`,
    image: '/project/medisea.svg',
    link: 'https://sea.com/shopee',
    tags: [
      'Go',
      'Docker',
      'SPACE',
      'React',
      'Nginx',
      'Vite.js',
      'Vitest',
      'Meilisearch',
      'Grafana',
      'k6',
      'TypeScript',
    ],
    year: 2025,
    author: {
      name: 'Achieva Futura Gemilang',
      avatar: '/AGLogoRevamped.png',
    },
    readTime: '8 min read',
    tldr: [
      'High-performance pharma marketplace with 100K+ MAU',
      'Sub-100ms latency using Go and optimized database queries',
      'Fault-tolerant payment system with circuit breakers',
      'Real-time search with Meilisearch',
    ],
    fullDescription: `Medisea is a comprehensive pharmaceutical marketplace designed to bridge the gap between pharmacies and consumers. Built during the Sea Labs program, it tackles the challenge of high-concurrency transactions and reliable inventory management. The platform features a robust backend capable of handling over 100k monthly active users with sub-100ms latency, ensuring a smooth user experience even during peak demand.

We utilized a microservices-inspired architecture (modular monolith) to ensure scalability while maintaining development velocity. The frontend, built with React and Vite, offers a snappy, responsive interface, while the Go backend ensures type safety and performance.`,
    features: [
      'Real-time drug inventory management',
      'Secure payment gateway integration',
      'Distance-based pharmacy search',
      'Prescription upload and verification flow',
      'Admin dashboard for order management',
    ],
    lessonsLearned: [
      'Importance of database indexing for query performance',
      'Strategies for handling distributed transactions',
      'Effective caching policies to reduce database load',
      'Writing comprehensive unit and integration tests',
    ],
  },

  {
    id: 10,
    title: 'Dare AI',
    slug: 'dare-ai',
    description: `An AI-powered party game that revitalizes the classic Truth or Dare experience with endlessly generated, creative challenges for social gatherings.`,
    image: '/project/dare-ai.png',
    link: 'https://dare-ai.lovable.app/',
    tags: ['Next.js', 'Lovable', 'Gemini API', 'TypeScript', 'Vite.js'],
    year: 2025,
    author: {
      name: 'Achieva Futura Gemilang',
      avatar: '/AGLogoRevamped.png',
    },
    readTime: '4 min read',
    tldr: [
      'AI-generated dares using Gemini API',
      'Real-time multiplayer experience',
      'Mobile-first responsive design',
    ],
    fullDescription: `Dare AI brings a modern twist to the classic party game. By leveraging Google's Gemini API, we generate context-aware, fun, and safe dares that adapt to the players' preferences. The project explores the potential of Generative AI in casual gaming and social interaction.`,
    features: [
      'AI-powered challenge generation',
      'Customizable difficulty levels',
      'Social sharing capabilities',
    ],
    lessonsLearned: [
      'Prompt engineering for consistent AI outputs',
      'Managing API rate limits and costs',
      'Building engaging mobile-first UI',
    ],
  },
  {
    id: 11,
    title: 'Dino Multiplayer',
    slug: 'dino-multiplayer',
    description:
      'A real-time, 1v1 competitive arcade game inspired by the classic Chrome Dino runner, synchronizing gameplay between two remote players.',
    image: '/project/dino-multiplayer.png',
    link: 'https://dino.achievagemilang.live',
    tags: [
      'Next.js',
      'Go',
      'WebSocket',
      'Docker',
      'PostgreSQL',
      'Redis',
      'Tailwind',
      'Caddy',
      'DigitalOcean',
    ],
    year: 2026,
    author: {
      name: 'Achieva Futura Gemilang',
      avatar: '/AGLogoRevamped.png',
    },
    readTime: '6 min read',
    tldr: [
      'Real-time 1v1 gameplay with deterministic lockstep',
      'Zero-latency synchronization using seeded RNG',
      'Scalable backend with Go and Microservices',
    ],
    fullDescription: `Dino Multiplayer is a real-time, 1v1 competitive arcade game inspired by the classic Chrome Dino runner. Unlike the single-player original, this application synchronizes gameplay between two remote players, allowing them to race against each other in real-time.

The application follows a Client-Server model with a Microservices-lite approach using Docker Compose. It uses a deterministic lockstep synchronization method to ensure fairness without high bandwidth usage.`,
    features: [
      'Real-time 1v1 Multiplayer',
      'Deterministic Lockstep Synchronization',
      'WebSocket Communication',
      'Anti-Cheat System',
      'Leaderboard with PostgreSQL',
    ],
    lessonsLearned: [
      'Implementing deterministic simulation for network efficiency',
      'Handling stateful WebSocket connections in Go',
      'Orchestrating microservices with Docker Compose',
      'Designing anti-cheat heuristics for client-side games',
    ],
  },
];
