export const aiKnowledgeBase = {
  professionalSummary: `
    I am Achieva Futura Gemilang, a passionate lifelong learner and software engineer with a strong background in mobile and backend development. People also call me Cip, Acip, Asheva, or Shev. I am equipped with business-driven mindset and am specialized in building dynamic, user-centric applications and thrive in collaborative, fast-paced environments. My goal is to create impactful digital solutions that blend technical excellence with great user experience. True to my roots, I'm a lifelong learner. Right now, I'm captivated by the potential of AI agents and am focused on applying them to build next-generation products. I also document my learning journey through public writing, sharing my thoughts, successes, and failures. I believe the most effective learning technique is to do so in public, contributing back to the incredibly supportive tech community along the way. I hope it encourages others to achieve their goals, regardless of their origin.
  `,
  skills: [
    'Flutter',
    'Kotlin',
    'Swift',
    'Golang',
    'Next.js',
    'Java',
    'Spring Boot',
    'Python',
    'Django',
    'React',
    'JavaScript',
    'TypeScript',
    'NestJS',
    'Tailwind CSS',
    'Docker',
    'Git',
    'CI/CD',
    'Project Management',
    'Product Management',
    'Product Strategy',
    'Agile Methodologies',
    'Communication',
    'Team Leadership',
    'System Design',
    'Data Structures',
    'Algorithms',
    'Database',
    'API Design',
    'RESTful API',
    'AWS',
    'GCP',
    'SQL',
    'MongoDB',
    'MySQL',
    'gRPC',
    'Postman',
    'Tableau',
    'Figma',
    'Canva',
    'PostgreSQL',
    'NoSQL',
    'Firebase',
    'Google API',
    'OpenAI',
  ],
  workExperience: [
    {
      company: 'Shopee - SEA Labs',
      role: 'Software Engineer Trainee',
      period: '2025 - Present',
      responsibilities: ['Learned full-stack web development using Go and React.'],
      achievements: [
        'Selected as one of 28+ trainees out of 1000+ applicants to attend twenty-week program held by Sea Labs Indonesia.',
      ],
    },
    {
      company: 'Bank Mandiri',
      role: 'Software Engineer Intern',
      period: 'Sep 2024 - Dec 2024',
      responsibilities: [
        'Contributed to the RPA KCTT project using UiPath, automating the KCTT reject data recapitulation process, reducing manual effort by approximately 80%',
        'Developed automation solutions for IPA uploading, streamlining workflows to handle 30+ uploads with zero errors post-implementation.',
      ],
      achievements: [
        'Achieved recognition as one of the top interns in the IT School program, standing out among 3/4 sessions for exceptional performance and contributions.',
      ],
    },
  ],
  projects: [
    {
      name: 'Citizen Journalism Mobile',
      description: `A flutter app designed to streamline news reporting, delivering real-time updates from TVRI.`,
      role: 'Mobile Engineer',
      tech: ['Flutter', 'Quill RTE', 'Cubit', 'Local Database'],
      link: 'https://play.google.com/store/apps/details?id=com.tvri.citizenjournalism&hl=en&pli=1',
    },
    {
      name: 'BikunTracker Mobile',
      description:
        'A flutter app designed to keep track of the mobilization of Bis Kuning (Bikun) in University of Indonesia.',
      role: 'Lead Mobile Developer',
      tech: ['Flutter', 'Websocket', 'Google API', 'Firebase'],
      link: 'https://bikun.ui.ac.id/',
    },
    {
      name: 'Questify',
      description:
        'A startup project that aims to empower academic community engagement through a redefined prize-based questionnaire platform.',
      role: 'Full Stack Developer',
      link: 'https://questify-ppl.vercel.app/',
      tech: ['Next.js', 'NestJS', 'TypeScript', 'TDD'],
    },
    {
      name: 'HouseSpot',
      description:
        'A mobile app designed to simplify homeownership by estimating house prices, connecting with reliable vendors, and discovering related home products and services.',
      role: 'Mobile Engineer',
      link: 'https://github.com/HouseSpot/kotlin-mobile-fe/releases',
      tech: ['Kotlin', 'Google API', 'ExpressJS', 'GCP'],
    },
  ],
  education: [
    {
      institution: 'Universitas Indonesia',
      degree: 'Bachelor of Computer Science',
      period: '2021 - 2025',
      achievements: [
        'Graduated with honors with a GPA of 3.74 (Cumlaude)',
        'Active in student organizations and tech communities: RISTEK CS UI, FUKI CS UI, COMPFEST, Pesta Rakyat Komputer, AIESEC, Teaching Assistant',
        'Thesis: Integration Between Product Line and Product Line Authentication Improvements After Dependency Changes in Prices-IDE (Grade: A)',
      ],
    },
  ],
  honors: [
    'Best Delegates Award Comparative Study Japan #2 - Leaders.id (2025)',
    'Top Contributor AIESEC Future Leaders Winter Peak - AIESEC University of Indonesia (2025)',
    'Best Lead of Mobile Development Q1 - RISTEK, Faculty of Computer Science University of Indonesia (2024)',
    'Finalist of National Informatics Olympiad - Ministry of Education, Culture, Research, and Technology (2020)',
  ],
  interests: [
    'Music',
    'Singing',
    'Reading',
    'Self-Improvement',
    'Gaming',
    'Mobile Legends',
    'Software Engineering',
  ],
  funFacts: [
    'I love to sing. It also means that I love doing music. I played guitar a little bit, but more proficient in singing. I mostly prefer Pop, RnB, J-Pop, and K-Pop music genres. You can find me singing on my Instagram highlight or through my TikTok: @asheva10.',
    'I love to read, especially when I am alone. Right now, I have read more than 50+ books. My favorite genre to read is Self-Improvement and Business. My favorite book is "The Alchemist" by Paulo Coelho. The reason why I love to read is because I believe that reading is the best way to network with amazing authors and learn new things from it. It\'s like having coffee chat with them.',
    'I love playing games, especially Mobile Legends, I achieved the highest rank in the game: Mythical Immortal. My signature hero is "Beatrix" with 75%+ win rate with 440+ games played.',
  ],
};
